#Testing, #Jest 

[Repo](https://github.com/pozafly/Jest-Example)

```js
function fetchProduct(error) {
  if (error === 'error') {
    return Promise.reject('network error');
  }
  return Promise.resolve({ item: 'Milk', price: 200 });
}

module.exports = fetchProduct;
```

이런 코드를 테스트 하자.

```js
it('async', () => {
  fetchProduct().then((item) => {
    expect(item).toEqual({ item: 'Milk', price: 200 });
  });
});
```
테스트 하면, 잘 통과가 된다. Object 형식이 return 될 것이기 때문에 `toEqual` 함수를 사용함. item 이름을 'Milk' 가 아니고, 'PPP' 라고 해보자. `expect(item).toEqual({ item: 'PPP', price: 200 });` 

> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason 

이런 warning이 뜬다. 하지만 테스트는 정상적으로 되었다. 이상하다. PPP 인데도 통과가 되었기 때문임.
다시 말하면 jest에서는 통과가 되었지만 promise 내부에서는 warning이 뜬 것.

살펴보자. `fetchProduct` 함수는 비동기 코드이기 때문에 .then 절이 오기 전에 it 함수는 끝이 난다. 그러면 jest 입장에서는 it 함수가 별도의 에러 없이 잘 통과 되었기 때문에 expect 없이 PASS 로 인식하는 것이다.

우리가 원하는 것은 fetchProduct 함수가 .then을 통해 비동기 코드가 완료 된 다음, expect 함수를 거쳐 테스트 완료 후 it 함수를 종료 시키는 것이다.

## 해결 방법(비동기 코드가 끝나는 시점을 jest에게 알려주기)

### done 방식
```js
it('async - done', (done) => {  // 🔥
  fetchProduct().then((item) => {
    expect(item).toEqual({ item: 'PPP', price: 200 });
    done();  // 🔥
  });
});
```
🔥 done을 인자로 받아, 끝나는 시점에 done() 함수를 호출해주기. 그러면 PPP 이므로 test가 실패하고, Milk로 바꿔주면 다시 성공 함.

하지만 약간 코드가 더러워 보임.

### return 방식
```js
it('async - return', () => {
  return fetchProduct().then((item) => {  // 아예 리턴해버림
    expect(item).toEqual({ item: 'Milk', price: 200 });
  });
});
```
그냥 promise를 리턴 해주면 된다.

이렇게 2가지 방식이 있는데 done은 시간이 훨씬 오래걸린다는 단점이 있다. return 방식으로 사용하도록 하자.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/59427983/194762824-f81142bf-261b-4081-b8f0-6b98717e8f92.png">

### async await 방식
```js
it('async - await', async () => {
  const product = await fetchProduct();
  expect(product).toEqual({ item: 'Milk', price: 200 });
});
```


---


### resolves 검사
```js
it('async - resolves', () => {
  return expect(fetchProduct()).resolves.toEqual({
    item: 'Milk',
    price: 200,
  });
});
```
expect를 return 해주고, resolves 라는 jest 함수를 체이닝 걸어주면 된다.

### reject 검사
```js
it('async - rejects', () => {
  return expect(fetchProduct('error')).rejects.toBe('network error');
});
```
이번엔 resolves 대신, rejects 를 체이닝을 걸어주고, reject 된 문구를 써주면 된다.